# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Android Gradle Build

on:
  push:
    branches: [ "dev-stage" ]
  pull_request:
    branches: [ "dev-stage" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Get secret
      env:
        JSON: ${{ secrets.JSON_PASS }}
      run: chmod +x ./decrypt.sh && ./decrypt.sh
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew :app:assembleRelease
    - name: Remove secret
      run: rm -rf app/google-services.json
